apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ctemp48/backend:9d8996c996891521fe553151c2e262f87e99fbd3
          ports:
            - containerPort: 8000
