apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ctemp48/backend:f216a016255b54af0900ffdb0a93e7d521123344
        ports:
        - containerPort: 8000
